### PR TITLE
#6, chapter01/solution1.6.1.1.scala

### PR DESCRIPTION
**Pull request by andreas-roehler**
As beginners are addressed, tried keeping it as simple a possible.

### CODE REVIEW

**Comment by andreas-roehler** [comment]
For sure, your more sophisticated solution would be nice to have also. As IMHO every task has an infinite number of solutions, maybe it's worth having an own directory for it?

**Comment by winitzki** [comment]
Right now the build is failing because `solution1.6.1.1.scala` is not a valid file for compilation. That file may be okay for loading by hand via `:load` but not for building the entire set of tests. We need to figure out how best to organize this workflow.

**Comment by winitzki** [comment]
I think the solutions in individual files will need to be in a separate directory, not together with the Scala tests. But then I am not sure how we can automatically make them compile.

**Comment by andreas-roehler** [comment]
Hmm, thought of a rather simple reference for the reader, for example as given for Example 2.1.5.8.

**Pull request merged**
