### PR TITLE
solution2.1.7.11a added

### PR DESCRIPTION
**Pull request by andreas-roehler**

### CODE REVIEW

**Review by winitzki — APPROVED** [review]

**Comment by winitzki** [comment]
Should this PR be merged or are you still working on it?

**Comment by andreas-roehler** [comment]
Thought being ready as part a.

**Comment by andreas-roehler** [comment]
Thought providing a solution2.1.7.11b afterwards. Maybe close this PR and have only one solution?

**Comment by andreas-roehler** [comment]
Nonetheless, may add the part b and rename, I you prefer this.

**Pull request merged**
